# Generated by Django 5.2.4 on 2025-07-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(default='', max_length=15)),
                ('rua', models.CharField(default='', max_length=100)),
                ('numero', models.CharField(default='', max_length=10)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('cep', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('modalidade', models.CharField(choices=[('loja', 'Consumo na Loja'), ('retirada', 'Retirada')], default='loja', max_length=20)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], default='dinheiro', max_length=20)),
                ('em_preparo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='confeitaria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(unique=True)),
                ('data_pedido', models.DateTimeField()),
                ('modalidade', models.CharField(choices=[('loja', 'Consumo na Loja'), ('retirada', 'Retirada')], max_length=20)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='confeitaria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_pedido', to='confeitaria.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confeitaria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoConcluidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_pedido_concluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confeitaria.pedidoconcluido')),
                ('id_produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='confeitaria.produto')),
            ],
        ),
    ]
