# Generated by Django 5.2.3 on 2025-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito')], default='Pix', max_length=50),
            preserve_default=False,
        ),
    ]
