# Generated by Django 5.2.3 on 2025-07-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoproduto',
            unique_together={('id_pedido', 'id_produto')},
        ),
    ]
