# Generated by Django 5.2.3 on 2025-07-14 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0002_alter_pedidoproduto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproduto',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_pedido', to='confeitaria.pedido'),
        ),
    ]
