# Generated by Django 5.2.4 on 2025-07-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0002_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoconcluido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoconcluido',
            name='forma_pagamento',
            field=models.CharField(default='dinheiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoconcluido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidoconcluido',
            name='id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoconcluido',
            name='modalidade',
            field=models.CharField(default='loja', max_length=20),
        ),
    ]
