# Generated by Django 5.2.4 on 2025-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0004_pedido_valor_total_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito')], default='pix', max_length=50),
        ),
    ]
