# Generated by Django 5.2.4 on 2025-07-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeitaria', '0006_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoconcluido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoconcluidoproduto',
            name='id_pedido_concluido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_concluidos', to='confeitaria.pedidoconcluido'),
        ),
    ]
